#!/bin/bash

main() {
    while read -r line; do
        binary "$line"
    done
}

binary() {
    local num=$1; shift
    local i=0
    while [[ "$i" != 16  ]]; do
        if [[ $(( 32768 & $num )) != 0 ]]
        then echo -n 1
        else echo -n 0
        fi
        : $(( num <<= 1 ))
        : $(( i += 1 ))
    done
    echo
}

main "$@"
