#!/bin/sh

MAXCYCLES=100000000
echo
echo '***' Running tests...

ISTTY=
if [ -t 1 ]; then
    ISTTY=yes
fi

main() {
    run=0
    pass=0
    fail=0

    for testpath # in args
    do
        test=$(basename "$testpath")
        printf '%s' "Running test: $test: "
        capture=$(sim65 -x "$MAXCYCLES" "$testpath" 2>&1)
        status=$?
        run=$(( $run + 1 ))
        if [ $status -eq 0 ]; then
            green PASS
            pass=$(( $pass + 1 ))
            if [ "${VERBOSE_TESTS-__none__}" != __none__ ]; then
                blab
            fi
        else
            red FAIL...
            fail=$(( $fail + 1 ))
            blab
        fi
    done

    #### Results! ####
    echo
    [ "$pass" -eq "$run" ]
    r=$?
    echo Final Results:
    passfail "$r" "Tests run   : $run"
    passfail "$r" "Tests passed: $pass"
    passfail "$r" "Tests failed: $fail"
}

blab() {
    msg=failed
    if [ "$status" -eq 0 ]; then msg=passed; fi
    echo
    echo "Exit code $status"
    echo
    if [ -n "$capture" ]; then
        echo "** Start of $msg $test output ***"
        printf '%s\n' "$capture" | sed 's/^/  /'
        echo "** End of $msg $test output ***"
    fi
}

green() {
    if [ -n "$ISTTY" ]; then
        printf '\033[32;1m%s\033[m\n' "$*"
    else
        printf '%s\n' "$*"
    fi
}

red() {
    if [ -n "$ISTTY" ]; then
        printf '\033[31m%s\033[m\n' "$*"
    else
        printf '%s\n' "$*"
    fi
}

passfail() {
    val=$1; shift
    if [ "$val" -eq 0 ]; then
        green "$*"
    else
        red   "$*"
    fi
}

main "$@"
