5 HOME
10  R$=CHR$(18):R$="/"
100 PRINT "IT'S BEEN A LONG, "; R$;
110 PRINT "L3:3:LONG"; R$
200 PRINT "DAY AT THE OFFICE, FILLED"
300 PRINT "YET AGAIN WITH BRIGHTLY FLASHING,"
350 PRINT "HEADACHE-INDUCING "; R$;
400 PRINT "VFLOURESCENT LIGHTS"; R$; "."
450 PRINT
500 PRINT "AS SOON AS YOU WALK THROUGH THE DOOR"
600 PRINT "TO YOUR HOME, YOU TOSS YOUR KEYS"
700 PRINT "ONTO THE TABLE AND, WITH A RESOUNDING"
730 PRINT "THUD, ";
750 PRINT R$; "DDROP"; R$; " INTO YOUR COUCH."
